{
 "title": "Mon API Dashboard",
 "refresh": "10s",
 "panels": [
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    { "expr": "sum(http_requests_total)", "legendFormat": "Total Requests" }
   ]
  },
  {
   "title": "Requests per Service",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Node.js Memory Usage",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 4, "w": 6, "h": 8 },
   "targets": [
    { "expr": "nodejs_heap_size_used_bytes", "legendFormat": "{{job}} heap used" }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 12, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=~\".*cat.*|.*dog.*\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}