upstream api_backend {
    server cat:3000;
    server dog:3000;
}

upstream cat_backend {
    server cat:3000;
}

upstream dog_backend {
    server dog:3000;
}

server {
    listen 80;

    location / {
        proxy_pass http://api_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /cat {
        proxy_pass http://cat_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /dog {
        proxy_pass http://dog_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
